apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: default
data:
  ES_URL: "https://elasticsearch-master.elastic.svc.cluster.local:9200"
  ES_USERNAME: "elastic"
  ES_PASSWORD: "elastic"