# The following code is heavily adapted from the python example generated by
# the Victorian State Government Department of Transport/VicRoads API website:
# https://data-exchange-test.vicroads.vic.gov.au/api-details#api=srods-disruptions-road-apiv1&operation=get-planneddisruptions

import requests, config

def main():

    all_data = []

    for disrupt_type in ["planned", "unplanned"]:

        header = {'Cache-Control': 'no-cache', 
                  'Ocp-Apim-Subscription-Key': config('DT_KEY')}
        
        if disrupt_type == "planned":
            url = "https://data-exchange-test-api.vicroads.vic.gov.au/opendata/disruptions/v1/planned?format=GeoJson"
        else:
            url = "https://data-exchange-test-api.vicroads.vic.gov.au/opendata/disruptions/v1/unplanned?format=GeoJson"

        data_chunk = requests.get(url, headers=header).json()

        data = data_chunk

        while data_chunk['nextPageDetails']['hasMoreRecords'] == "true":
            header['NextPageToken'] = data['nextPageDetails']['nextPageToken']
            data_chunk = requests.get(url, headers=header).json()
            data['features'] += data_chunk['features']

        all_data.append(data)
    
    return all_data