include:
- ./chronic_lga_disease.py
- ./requirements.txt
- ./build.sh
kind: ArchiveUploadSpec
name: chronic-lga-disease-py-UXdU

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: chronicdiseases
spec:
  buildcmd: ./build.sh
  deployment:
    checksum: {}
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
    type: url
    url: archive://chronic-lga-disease-py-UXdU
status:
  buildstatus: pending
  lastUpdateTimestamp: "2024-05-15T08:03:24Z"
