apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: diseasescountbylga
spec:
  createingress: false
  functionref:
    functionweights: null
    name: chronicdiseases
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /diseasescount/lga/{lga:[a-zA-Z0-9_]+}
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /diseasescount/lga/{lga:[a-zA-Z0-9_]+}
